use_infonce_loss: False
use_golden_loss: False
golden_loss_weight: 0.001
get_hidden_state: False
layer_list: []
add_mlp:
add_mlp_golden:
mlp_intermidiate_size:
norm_embeddings: False
mlp_golden: False
golden_loss_scheduler_type: constant
align_type: last_token
loss_type: cosine
golden_from: None