use_infonce_loss: False
use_golden_loss: False
golden_loss_weight: 0.001
get_hidden_state: False
layer_list: []
add_mlp:
mlp_intermidiate_size:
normalize_golden_loss: False
mlp_golden: False
golden_loss_scheduler_type: constant