use_infonce_loss: False
use_golden_loss: False
golden_loss_weight: 0.001
get_hidden_state: False
layer_list: []
add_mlp: False
add_mlp_golden: False
add_attention_pooling: False
mlp_intermidiate_size:
norm_embeddings: False
mlp_golden: False
golden_loss_scheduler_type: constant
align_type: last_token
loss_type: cosine
golden_from: None
use_repa_in_reward: False
hidden_state_size: 0
layernorm: False
eta_min: 0
dynamic_layer_type: None