#!/bin/bash
n_nodes=1
export SWANLAB_MODE=offline
export HYDRA_FULL_ERROR=1
# export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:False
export DATA_PATH=/p/project/hai_pri_self/jizhe/verl/datasets
export HF_ENDPOINT="https://hf-mirror.com"
export ACCELERATE_LOG_LEVEL=info
export MODEL_PATH=/p/project/hai_pri_self/jizhe/models/Qwen/Qwen2.5-3B
dapo_train_path="${DATA_PATH}/math_gold/train.parquet"
math500_test_path="${DATA_PATH}/math500/test.parquet"
train_files="['$dapo_train_path']"
test_files="['$math500_test_path']"
total_epochs=5
cliph=0.28
run_name=mj_ep${total_epochs}_math_num8_base_len4k_cliph${cliph}
save_root=/p/project/hai_pri_self/jizhe/verl_results/Qwen2.5-3B/$run_name
PYTHONUNBUFFERED=1 python3 -m verl.trainer.main_ppo \
    algorithm.adv_estimator=grpo \
    data.train_files="$train_files" \
    data.val_files="$test_files" \
    data.train_batch_size=512 \
    data.max_prompt_length=512 \
    data.max_response_length=4096 \
    data.filter_overlong_prompts=True \
    data.filter_overlong_prompts_workers=64 \
    data.truncation='error' \
    data.return_full_prompt=True \
    actor_rollout_ref.model.path=${MODEL_PATH} \
    actor_rollout_ref.model.use_fused_kernels=False \
    actor_rollout_ref.actor.optim.lr=1e-6 \
    actor_rollout_ref.actor.clip_ratio_low=0.2 \
    actor_rollout_ref.actor.clip_ratio_high=${cliph} \
    actor_rollout_ref.actor.clip_ratio_c=10.0 \
    actor_rollout_ref.actor.optim.warmup_style=cosine \
    actor_rollout_ref.actor.optim.lr_warmup_steps=10 \
    actor_rollout_ref.actor.optim.weight_decay=0.1 \
    actor_rollout_ref.actor.grad_clip=1.0 \
    actor_rollout_ref.model.use_remove_padding=True \
    actor_rollout_ref.actor.use_kl_loss=False \
    actor_rollout_ref.actor.kl_loss_coef=0.0 \
    actor_rollout_ref.actor.kl_loss_type=low_var_kl \
    actor_rollout_ref.actor.use_dynamic_bsz=False \
    actor_rollout_ref.actor.ppo_mini_batch_size=32 \
    actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=4 \
    actor_rollout_ref.actor.entropy_coeff=0 \
    actor_rollout_ref.model.enable_gradient_checkpointing=True \
    actor_rollout_ref.actor.fsdp_config.param_offload=False \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=False \
    actor_rollout_ref.rollout.name=vllm \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.8 \
    actor_rollout_ref.rollout.log_prob_use_dynamic_bsz=False \
    actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=4 \
    actor_rollout_ref.rollout.n=8 \
    actor_rollout_ref.rollout.tensor_model_parallel_size=1 \
    actor_rollout_ref.ref.fsdp_config.param_offload=True \
    actor_rollout_ref.rollout.temperature=1.0 \
    actor_rollout_ref.rollout.top_p=1.0 \
    actor_rollout_ref.rollout.top_k=-1 \
    actor_rollout_ref.rollout.val_kwargs.temperature=1.0 \
    actor_rollout_ref.rollout.val_kwargs.top_p=0.7 \
    actor_rollout_ref.rollout.val_kwargs.top_k=-1 \
    actor_rollout_ref.rollout.val_kwargs.do_sample=True \
    actor_rollout_ref.rollout.val_kwargs.n=1 \
    algorithm.use_kl_in_reward=False \
    trainer.critic_warmup=0 \
    trainer.n_gpus_per_node=4 \
    trainer.nnodes=${n_nodes} \
    trainer.logger=['console','swanlab'] \
    trainer.project_name=DAPO-Qwen2.5-3B \
    trainer.experiment_name=$run_name \
    trainer.save_freq=50 \
    trainer.test_freq=5 \
    trainer.total_epochs=${total_epochs} \
    trainer.default_local_dir=${save_root}/model \
    trainer.rollout_data_dir=${save_root}/rollout \
    trainer.validation_data_dir=${save_root}/val_data \
    trainer.val_before_train=False \
    actor_rollout_ref.actor.fsdp_config.use_orig_params=True